#!/usr/bin/env python3
"""Turn data/compiler-overrides.json into target-specific make variables.

Parts of the ROM were not built with the default toolchain. The Makefile's
`$(BUILD_DIR)/%.o: %.c` recipe expands $(CC1) and $(CFLAGS) when it runs, so a
target-specific assignment on one object redirects just that object:

    build/src/decomp/c_080713F8.o: CC1 := tools/agbcc/bin/old_agbcc

tools/agbenv.py reads the same JSON so trymatch.py and compile_probe agree with
the build. Keeping one source of truth is the point: an override the build knows
about and the verifier does not makes every later wave re-attempt a function
that is already solved and conclude it cannot be matched.

    python tools/gen_overrides_mk.py
"""

import json
import os
import sys

import awlib

OVERRIDES = os.path.join(awlib.DATA_DIR, "compiler-overrides.json")
PROMOTED = os.path.join(awlib.DATA_DIR, "promoted.json")
OUT = os.path.join(awlib.REPO, "build", "compiler-overrides.mk")


def load(path, default):
    if not os.path.exists(path):
        return default
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def main():
    overrides = load(OVERRIDES, {}).get("functions", {})
    promoted = load(PROMOTED, [])

    by_fn = {}
    for entry in promoted:
        for fn in entry["functions"]:
            by_fn[fn] = entry

    lines = ["# Generated by tools/gen_overrides_mk.py -- do not edit.",
             "# Source of truth: data/compiler-overrides.json", ""]
    emitted = skipped = 0

    for fn in sorted(overrides):
        ov = overrides[fn]
        entry = by_fn.get(fn)
        if entry is None:
            skipped += 1
            continue

        # Flags apply per object file. If the override shared a file with other
        # functions they would silently be rebuilt with the wrong toolchain, and
        # the ROM hash would be the first thing to notice. Refuse instead.
        if len(entry["functions"]) > 1:
            others = [n for n in entry["functions"] if n != fn]
            sys.stderr.write(
                "error: %s needs a compiler override but shares %s with %s.\n"
                "       An overridden function must sit in a .c file of its own;\n"
                "       promote it separately.\n"
                % (fn, entry["file"], ", ".join(others)))
            return 1

        obj = "$(BUILD_DIR)/%s" % entry["obj"]
        lines.append("# %s" % fn)
        if ov.get("cc1"):
            lines.append("%s: CC1 := $(AGBCC_HOME)/bin/%s$(EXE)" % (obj, ov["cc1"]))
        removals = ov.get("cflags_remove", ())
        additions = ov.get("cflags_add", ())
        if removals or additions:
            expr = "$(CFLAGS)"
            for opt in removals:
                expr = "$(filter-out %s,%s)" % (opt, expr)
            for opt in additions:
                expr = "%s %s" % (expr, opt)
            lines.append("%s: CFLAGS := %s" % (obj, expr))
        lines.append("")
        emitted += 1

    awlib.write_text(OUT, "\n".join(lines) + "\n")
    print("wrote %s  (%d override%s%s)"
          % (os.path.relpath(OUT, awlib.REPO), emitted,
             "" if emitted == 1 else "s",
             ", %d not yet promoted" % skipped if skipped else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
