#!/usr/bin/env python3
"""Turn data/compiler-overrides.json into target-specific make variables.

Parts of the ROM were not built with the default toolchain. The Makefile's
`$(BUILD_DIR)/%.o: %.c` recipe expands $(CC1) and $(CFLAGS) when it runs, so a
target-specific assignment on one object redirects just that object:

    build/src/decomp/c_080713F8.o: CC1 := tools/agbcc/bin/old_agbcc

tools/agbenv.py reads the same JSON so trymatch.py and compile_probe agree with
the build. Keeping one source of truth is the point: an override the build knows
about and the verifier does not makes every later wave re-attempt a function
that is already solved and conclude it cannot be matched.

    python tools/gen_overrides_mk.py
"""

import json
import os
import sys

import awlib

OVERRIDES = os.path.join(awlib.DATA_DIR, "compiler-overrides.json")
PROMOTED = os.path.join(awlib.DATA_DIR, "promoted.json")
OUT = os.path.join(awlib.REPO, "build", "compiler-overrides.mk")


def load(path, default):
    if not os.path.exists(path):
        return default
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def main():
    overrides = load(OVERRIDES, {}).get("functions", {})
    promoted = load(PROMOTED, [])

    by_fn = {}
    for entry in promoted:
        for fn in entry["functions"]:
            by_fn[fn] = entry

    lines = ["# Generated by tools/gen_overrides_mk.py -- do not edit.",
             "# Source of truth: data/compiler-overrides.json", ""]
    emitted = skipped = 0
    emitted_objs = set()

    for fn in sorted(overrides):
        ov = overrides[fn]
        entry = by_fn.get(fn)
        if entry is None:
            skipped += 1
            continue

        # Flags apply per object file. If the override shared a file with other
        # functions they would silently be rebuilt with the wrong toolchain, and
        # the ROM hash would be the first thing to notice. Refuse instead.
        #
        # WAVE 38: refuse only when the co-residents disagree. The check used to
        # be `len(entry["functions"]) > 1`, which also rejected the case where
        # EVERY function in the unit carries the SAME override -- and there the
        # object is compiled with exactly the toolchain all of them want, so the
        # hazard this check exists for cannot occur. W38-A matched sub_08071584
        # and sub_080715F8, both m4a, both needing old_agbcc, and promote.py
        # merged them into one unit; the old check then made a correct pair
        # unbuildable and the only remedy on offer ("promote it separately") was
        # to fight promote.py's own unit layout.
        # Compare the FLAGS, not the whole entry -- `reason` is prose and is
        # different for every function by design, so comparing entries whole
        # made two identically-configured functions look like a conflict.
        def toolchain(o):
            if not o:
                return None
            return (o.get("cc1"),
                    tuple(o.get("cflags_remove", ())),
                    tuple(o.get("cflags_add", ())))

        others = [n for n in entry["functions"] if n != fn]
        disagree = [n for n in others
                    if toolchain(overrides.get(n)) != toolchain(ov)]
        if disagree:
            sys.stderr.write(
                "error: %s needs a compiler override but shares %s with %s,\n"
                "       which %s a DIFFERENT override (or none). Flags apply to\n"
                "       the whole object, so promote it into a .c of its own.\n"
                % (fn, entry["file"], ", ".join(disagree),
                   "carries" if len(disagree) == 1 else "carry"))
            return 1

        obj = "$(BUILD_DIR)/%s" % entry["obj"]
        if obj in emitted_objs:
            continue          # a co-resident with the identical override
        emitted_objs.add(obj)
        lines.append("# %s" % fn)
        if ov.get("cc1"):
            lines.append("%s: CC1 := $(AGBCC_HOME)/bin/%s$(EXE)" % (obj, ov["cc1"]))
        removals = ov.get("cflags_remove", ())
        additions = ov.get("cflags_add", ())
        if removals or additions:
            expr = "$(CFLAGS)"
            for opt in removals:
                expr = "$(filter-out %s,%s)" % (opt, expr)
            for opt in additions:
                expr = "%s %s" % (expr, opt)
            lines.append("%s: CFLAGS := %s" % (obj, expr))
        lines.append("")
        emitted += 1

    # WAVE 38: write only when the CONTENT changes, so the file's mtime means
    # "the override set changed" and nothing else. The Makefile makes every C
    # object depend on this file -- an unconditional rewrite would rebuild the
    # whole tree every wave, because data/promoted.json is a prerequisite here
    # and that changes every wave.
    text = "\n".join(lines) + "\n"
    unchanged = (os.path.exists(OUT)
                 and open(OUT, encoding="utf-8").read() == text)
    if not unchanged:
        awlib.write_text(OUT, text)
    print("%s %s  (%d override%s%s)"
          % ("unchanged" if unchanged else "wrote  ",
             os.path.relpath(OUT, awlib.REPO), emitted,
             "" if emitted == 1 else "s",
             ", %d not yet promoted" % skipped if skipped else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
